# Generated by Django 5.0.6 on 2026-07-09 14:39

from django.db import migrations, models

# Old internal profile codes -> explicit specialization slugs.
_FORWARD = {"M1": "mate-info", "M2": "tehnologic", "M3": "pedagogic"}
_REVERSE = {v: k for k, v in _FORWARD.items()}


def _remap(model, mapping):
    for old, new in mapping.items():
        model.objects.filter(profile=old).update(profile=new)


def forwards(apps, schema_editor):
    _remap(apps.get_model("exercises", "ExerciseSession"), _FORWARD)


def backwards(apps, schema_editor):
    _remap(apps.get_model("exercises", "ExerciseSession"), _REVERSE)


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesession',
            name='profile',
            field=models.CharField(max_length=32),
        ),
        migrations.RunPython(forwards, backwards),
    ]
