# Generated by Django 5.0.6 on 2026-07-09 14:39

from django.db import migrations, models

# Old internal profile codes -> explicit specialization slugs. The old accounts
# labels were stale (M2 was mislabeled "Științele Naturii", M3 "Pedagogic /
# Tehnologic"); the engine has always treated M2=tehnologic, M3=pedagogic, so we
# migrate by that authoritative mapping. Users can now pick the genuine
# ``stiintele-naturii`` level once it is added.
_FORWARD = {"M1": "mate-info", "M2": "tehnologic", "M3": "pedagogic"}
_REVERSE = {v: k for k, v in _FORWARD.items()}


def _remap(model, mapping):
    for old, new in mapping.items():
        model.objects.filter(profile=old).update(profile=new)


def forwards(apps, schema_editor):
    _remap(apps.get_model("accounts", "User"), _FORWARD)


def backwards(apps, schema_editor):
    _remap(apps.get_model("accounts", "User"), _REVERSE)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('mate-info', 'Matematică–Informatică'), ('tehnologic', 'Tehnologic'), ('pedagogic', 'Pedagogic')], default='mate-info', max_length=32),
        ),
        migrations.RunPython(forwards, backwards),
    ]
