# Generated by Django 5.0.6 on 2026-07-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('mate-info', 'Matematică–Informatică'), ('stiintele-naturii', 'Științele Naturii'), ('tehnologic', 'Tehnologic'), ('pedagogic', 'Pedagogic')], default='mate-info', max_length=32),
        ),
    ]
