# Generated by Django 5.0.6 on 2026-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downloaded_pdfs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='generated_problems',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='generated_tests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
