# Generated by Django 5.0.6 on 2026-07-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_downloaded_pdfs_user_generated_problems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_session_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
