# Generated by Django 5.0.6 on 2026-07-13 14:40

from django.db import migrations, models


def grandfather_existing(apps, schema_editor):
    """Accounts that already exist predate email confirmation — mark them
    verified so this change doesn't lock anyone out."""
    User = apps.get_model("accounts", "User")
    User.objects.update(is_email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_active_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(grandfather_existing, migrations.RunPython.noop),
    ]
